name: Deploy to ECS
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set Environment Variables
        run: |
          if [ "${{ inputs.environment }}" = "development" ]; then
            echo "ECS_HOST=${{ secrets.DEV_ECS_HOST }}" >> $GITHUB_ENV
            echo "SSH_KEY=${{ secrets.DEV_ECS_SSH_KEY }}" >> $GITHUB_ENV
          elif [ "${{ inputs.environment }}" = "staging" ]; then
            echo "ECS_HOST=${{ secrets.STG_ECS_HOST }}" >> $GITHUB_ENV
            echo "SSH_KEY=${{ secrets.STG_ECS_SSH_KEY }}" >> $GITHUB_ENV
          elif [ "${{ inputs.environment }}" = "production" ]; then
            echo "ECS_HOST=${{ secrets.PROD_ECS_HOST }}" >> $GITHUB_ENV
            echo "SSH_KEY=${{ secrets.PROD_ECS_SSH_KEY }}" >> $GITHUB_ENV
          fi

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ env.SSH_KEY }}

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Deploy Container
        env:
          IMAGE_URI: '${{ secrets.ACR_REGISTRY }}/crazy_ryan/joy-of-energy:latest'
        run: |
          echo "Deploying to the ${{ inputs.environment }} environment..."
          ssh -o StrictHostKeyChecking=no root@${{ env.ECS_HOST }} << EOF
          docker pull $IMAGE_URI
          docker stop app || true
          docker rm app || true
          docker run -d --name app -p 8020:8020 $IMAGE_URI
          EOF
