name: Deploy to ECS
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Environment Secrets
        run: |
          if [[ "${{ inputs.environment }}" == "development" ]]; then
            echo "ECS_HOST=${{ secrets.DEV_ECS_HOST }}" >> $GITHUB_ENV
            echo "ECS_SSH_KEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.DEV_ECS_SSH_KEY }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          elif [[ "${{ matrix.env }}" == "staging" ]]; then
            echo "ECS_HOST=${{ secrets.STG_ECS_HOST }}" >> $GITHUB_ENV
            echo "ECS_SSH_KEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.STG_ECS_SSH_KEY }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          elif [[ "${{ matrix.env }}" == "production" ]]; then
            echo "ECS_HOST=${{ secrets.PROD_ECS_HOST }}" >> $GITHUB_ENV
            echo "ECS_SSH_KEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.PROD_ECS_SSH_KEY }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: $ECS_SSH_KEY

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Deploy Container
        env:
          IMAGE_URI: '${{ secrets.ACR_REGISTRY }}/crazy_ryan/joy-of-energy:latest'
        run: |
          echo "Deploying to the ${{ inputs.environment }} environment..."
          ssh -o StrictHostKeyChecking=no root@$ECS_HOST << EOF
          docker pull $IMAGE_URI
          docker stop app || true
          docker rm app || true
          docker run -d --name app -p 8020:8020 $IMAGE_URI
          EOF
