name: Deploy to ECS
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - env: development
            ecs_host: ${{ secrets.DEV_ECS_HOST }}
            ecs_ssh_key: ${{ secrets.DEV_ECS_SSH_KEY }}
          - env: staging
            ecs_host: ${{ secrets.STG_ECS_HOST }}
            ecs_ssh_key: ${{ secrets.STG_ECS_SSH_KEY }}
          - env: production
            ecs_host: ${{ secrets.PROD_ECS_HOST }}
            ecs_ssh_key: ${{ secrets.PROD_ECS_SSH_KEY }}

    if: inputs.environment == matrix.config.env

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ matrix.config.ecs_ssh_key }}

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Deploy Container
        env:
          ECS_HOST: ${{ matrix.config.ecs_host }}
          IMAGE_URI: '${{ secrets.ACR_REGISTRY }}/crazy_ryan/joy-of-energy:latest'
        run: |
          echo "Deploying to ${{ inputs.environment }}..."
          ssh -o StrictHostKeyChecking=no root@$ECS_HOST << EOF
          docker pull $IMAGE_URI
          docker stop app || true
          docker rm app || true
          docker run -d --name app -p 8020:8020 $IMAGE_URI
          EOF
