name: Deploy to ECS
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production
      tag:
        description: 'Docker image tag to deploy (SHA or git tag like v1.0.0)'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set Environment Variables
        run: |
          if [ "${{ inputs.environment }}" = "development" ]; then
            echo "ECS_HOST=${{ secrets.DEV_ECS_HOST }}" >> $GITHUB_ENV
            echo "API_KEY_DIGEST_TO_USER=${{ secrets.DEV_API_KEY_DIGEST_TO_USER }}" >> $GITHUB_ENV
          elif [ "${{ inputs.environment }}" = "staging" ]; then
            echo "ECS_HOST=${{ secrets.STG_ECS_HOST }}" >> $GITHUB_ENV
            echo "API_KEY_DIGEST_TO_USER=${{ secrets.STG_API_KEY_DIGEST_TO_USER }}" >> $GITHUB_ENV
          elif [ "${{ inputs.environment }}" = "production" ]; then
            echo "ECS_HOST=${{ secrets.PROD_ECS_HOST }}" >> $GITHUB_ENV
            echo "API_KEY_DIGEST_TO_USER=${{ secrets.PROD_API_KEY_DIGEST_TO_USER }}" >> $GITHUB_ENV
          fi

      - name: Configure Development SSH
        if: inputs.environment == 'development'
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEV_ECS_SSH_KEY }}

      - name: Configure Staging SSH
        if: inputs.environment == 'staging'
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.STG_ECS_SSH_KEY }}

      - name: Configure Production SSH
        if: inputs.environment == 'production'
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PROD_ECS_SSH_KEY }}

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Validate Image Exists
        run: |
          echo "Checking if image ${{ secrets.ACR_REGISTRY }}/crazy_ryan/joy-of-energy:${{ inputs.tag }} exists..."
          if ! docker pull ${{ secrets.ACR_REGISTRY }}/crazy_ryan/joy-of-energy:${{ inputs.tag }} > /dev/null 2>&1; then
            echo "❌ Image ${{ secrets.ACR_REGISTRY }}/crazy_ryan/joy-of-energy:${{ inputs.tag }} not found!"
            exit 1
          fi
          echo "✅ Image found successfully"

      - name: Deploy Container
        env:
          IMAGE_URI: '${{ secrets.ACR_REGISTRY }}/crazy_ryan/joy-of-energy:${{ inputs.tag }}'
        run: |
          echo "Deploying tag ${{ inputs.tag }} to the ${{ inputs.environment }} environment..."
          ssh -o StrictHostKeyChecking=no root@${{ env.ECS_HOST }} << EOF
          docker pull $IMAGE_URI
          docker stop app || true
          docker rm app || true
          docker run -d --name app -p 8020:8020 -e API_KEY_DIGEST_TO_USER='${{ env.API_KEY_DIGEST_TO_USER }}' $IMAGE_URI
          EOF
